basePath: /api
definitions:
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.BadRequestErrorResponse:
    description: Example for a 400 Invalid Input response
    properties:
      code:
        example: BAD_REQUEST
        type: string
      details:
        example: Please check your input and try again
        type: string
      message:
        example: invalid email format
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ConflictErrorResponse:
    description: Example for a 409 User Already Exists response
    properties:
      code:
        example: CONFLICT
        type: string
      details:
        example: Please check your input and try again
        type: string
      message:
        example: user already exists
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.DetailedErrorResponse:
    description: Resposta de erro detalhada com código, mensagem e detalhes adicionais
    properties:
      code:
        allOf:
        - $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ErrorCode'
        example: VALIDATION_FAILED
      details:
        example: The provided email address is not valid
        type: string
      message:
        example: Invalid email format
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ErrorCode:
    enum:
    - INVALID_REQUEST
    - INVALID_CREDENTIALS
    - VALIDATION_FAILED
    - USER_ALREADY_EXISTS
    - DATABASE_ERROR
    - INTERNAL_ERROR
    - USER_NOT_FOUND
    - TOKEN_INVALID
    - TOKEN_EXPIRED
    - INVALID_SIGNING_METHOD
    type: string
    x-enum-varnames:
    - ErrorCodeInvalidRequest
    - ErrorCodeInvalidCredentials
    - ErrorCodeValidationFailed
    - ErrorCodeUserExists
    - ErrorCodeDatabaseError
    - ErrorCodeInternalError
    - ErrorCodeUserNotFound
    - ErrorCodeTokenInvalid
    - ErrorCodeTokenExpired
    - ErrorCodeInvalidSigningMethod
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ForbiddenErrorResponse:
    description: Example for a 403 Invalid Credentials response
    properties:
      code:
        example: FORBIDDEN
        type: string
      details:
        example: Please check your credentials and try again
        type: string
      message:
        example: Invalid credentials
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.InternalServerErrorResponse:
    description: Example for a 500 Internal Server Error response
    properties:
      code:
        example: INTERNAL_SERVER_ERROR
        type: string
      details:
        example: failed to create user
        type: string
      message:
        example: Internal server error
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.LoginRequest:
    description: Login credentials for user authentication
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: securePassword123
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.SignupRequest:
    description: User registration information
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: securePassword123
        type: string
    type: object
  github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.TokenResponse:
    description: JWT token returned upon successful authentication
    properties:
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for DT Labs Fullstack Exam - Device Management System
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: DT Labs Exam API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Returns JWT token
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.TokenResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.DetailedErrorResponse'
        "403":
          description: Invalid credentials
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ForbiddenErrorResponse'
      summary: User login
      tags:
      - authentication
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Register a new user and return JWT token
      parameters:
      - description: User registration information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.SignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Returns JWT token
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.TokenResponse'
        "400":
          description: Invalid email format or password too short
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.BadRequestErrorResponse'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.ConflictErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Arthur-7Melo_exame-fullstack-setembro-dtlabs-2025_internal_dto.InternalServerErrorResponse'
      summary: User registration
      tags:
      - authentication
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
